---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookingservice
    spec:
      containers:
      - name: bookingservice
        image: [your-name-here]/bookingservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3010
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_URLS
            value: http://*:3010
          - name: ConnectionStrings__sqlestateagentdata
            value: "Server=sqlestateagentbookingdata;Database=EABooking;User Id=sa;Password=PaSSw0rdPaSSw0rd;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True"
          - name: PROPERTYSERVICE
            value: http://propertyservice:3012
          - name: BUYERSERVICE
            value: http://buyerservice:3011
  selector:
    matchLabels:
      app: bookingservice

---
apiVersion: v1
kind: Service
metadata:
  name: bookingservice
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3010
    targetPort: 3010
    nodePort: 32010
  selector:
    app: bookingservice