---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: propertyservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: propertyservice
    spec:
      containers:
      - name: propertyservice
        image: [your-name-here]/propertyservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3012
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: http://*:3012
        - name: ConnectionStrings__sqlestateagentdata
          value: "Server=sqlestateagentpropertydata;Database=EAProperty;User Id=sa;Password=PaSSw0rdPaSSw0rd;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True"
  selector:
    matchLabels:
      app: propertyservice

---
apiVersion: v1
kind: Service
metadata:
  name: propertyservice
spec:
  type: NodePort
  ports:
  - port: 3012
    targetPort: 3012
    nodePort: 32012
  selector:
    app: propertyservice