---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: shopping2022backend-deploy
    labels:
        app: shopping2022backend
spec:
  replicas: 1
  #strategy:
  #  type: RollingUpdate
  #  rollingUpdate:
  #      maxSurge: 1
  #      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: shopping2022backend
    spec:
      containers:
      - name: shopping2022backend
        image: pbehague/shoppingservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        env:
        - name: ASPNETCORE_URLS
          value: http://*:5003
  selector:
    matchLabels:
      app: shopping2022backend

---
apiVersion: v1
kind: Service
metadata:
  name: shopping2022backend
spec:
  type: NodePort
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 32003
  selector:
    app: shopping2022backend
    