apiVersion: apps/v1
kind: Deployment
metadata:
 name: sqlestateagentpropertydata 
spec:
 replicas: 1 
 selector:
  matchLabels:
   app: sqlestateagentpropertydata
 template:
  metadata:
   labels:
    app: sqlestateagentpropertydata
  spec:
   containers:
   - name: sqlestateagentpropertydata
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
     - containerPort: 1433
     env:
     - name: ACCEPT_EULA
       value: "Y"
     - name: SA_PASSWORD
       value: "PaSSw0rdPaSSw0rd"
---
apiVersion: v1
kind: Service
metadata:
  name: sqlestateagentpropertydata
spec:
  type: NodePort
  selector:
    app: sqlestateagentpropertydata
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tcpsql
