apiVersion: apps/v1
kind: Deployment
metadata:
 name: sqlestateagentbuyerdata # name of the StatefulSet workload, the SQL Server instance name is derived from this. We suggest to keep this name same as the .spec.template.metadata.labels, .spec.selector.matchLabels and .spec.serviceName to avoid confusion.
spec:
 replicas: 1 # only one pod, with one SQL Server instance deployed.
 selector:
  matchLabels:
   app: sqlestateagentbuyerdata  # this has to be the same as .spec.template.metadata.labels
 template:
  metadata:
   labels:
    app: sqlestateagentbuyerdata # this has to be the same as .spec.selector.matchLabels, as documented [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/):
  spec:
   containers:
   - name: sqlestateagentbuyerdata # container name within the pod.
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
     - containerPort: 1433
     env:
     - name: ACCEPT_EULA
       value: "Y"
     - name: SA_PASSWORD
       value: "PaSSw0rdPaSSw0rd"
---
apiVersion: v1
kind: Service
metadata:
  name: sqlestateagentbuyerdata
spec:
  type: NodePort
  selector:
    app: sqlestateagentbuyerdata
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tcpsql